apiVersion: v1
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - ${metallbip}
    - name: tsb
      protocol: layer2
      addresses:
      - ${metallbip2}
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system