---
apiversion: application.tsb.tetrate.io/v2
kind: Application
metadata:
  organization: tetrate
  tenant: tetrate
  name: helloworld
spec:
  displayName: Helloworld
  description: Helloworld application
  workspace: organizations/tetrate/tenants/tetrate/workspaces/helloworld
---
apiversion: application.tsb.tetrate.io/v2
kind: API
metadata:
  organization: tetrate
  tenant: tetrate
  application: helloworld
  name: helloworld
spec:
  displayName: Helloworld API
  description: Helloworld API
  workloadSelector:
    namespace: helloworld
    labels:
      app: helloworld-gateway
      istio: ingressgateway
  openapi: |
    openapi: 3.0.0
    info:
      title: Helloworld API
      description: An HTTP API that replies with a Hello World message
      version: "1.0"
      x-tsb-service: helloworld.helloworld
    servers:
      - url: https://hello.world
        x-tsb-tls:
          mode: SIMPLE
          secretName: helloworld-certs
      - url: http://plain.hello.world
    paths:
      /hello:
        get:
          summary: Returns a Hello World string with the details of the pod serving the request
          responses:
            '200':
              description: A JSON array of user names
              content:
                text/plain:
                  schema:
                    type: string
      /health:
        get:
          summary: Returns a healthy message
          reponses:
            '200':
              description: A healthy message
              content:
                text/plain:
                  schema:
                    type: string
      /v2/hello:
        x-tsb-redirect:
          uri: /hello
        get:
          summary: New version of hello world
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: ApplicationAccessBindings
metadata:
  organization: tetrate
  tenant: tetrate
  application: helloworld
spec:
  allow:
    - role: rbac/creator
      subjects:
        - user: admin
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: APIAccessBindings
metadata:
  organization: tetrate
  tenant: tetrate
  application: helloworld
  api: helloworld
spec:
  allow:
    - role: rbac/creator
      subjects:
        - user: admin
