apiVersion: api.tsb.tetrate.io/v2
kind: Organization
metadata:
  name: tetrate
spec:
  displayName: Tetrate
  description: Tetrate organization
---
apiVersion: api.tsb.tetrate.io/v2
kind: Tenant
metadata:
  organization: tetrate
  name: tetrate
spec:
  displayName: Tetrate
  description: Tetrate tenant
---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  organization: tetrate
  tenant: tetrate
  name: helloworld
spec:
  displayName: Helloworld
  description: Helloworld application
  namespaceSelector:
    names:
      - "*/helloworld"
