---
apiVersion: install.tetrate.io/v1alpha1
kind: ManagementPlane
metadata:
  name: managementplane
  namespace: tsb
spec:
  hub: ${reg}
  organization: tetrate
  telemetryStore:
    elastic:
      host: ${elastic_host}
      port: 9200
      version: 7
      protocol: https
      selfSigned: true
  components:
    apiServer:
      teamSyncSchedule: 0 * * * *
    frontEnvoy:
      kubeSpec:
        service:
          annotations:
            metallb.universe.tf/address-pool: tsb
          type: LoadBalancer
    xcp:
      kubeSpec:
        overlays:
        - apiVersion: install.xcp.tetrate.io/v1alpha1
          kind: CentralXcp
          name: central-xcp
          patches:
          - path: spec.components.centralServer.kubeSpec.service.annotations
            value:
              metallb.universe.tf/address-pool: tsb
          - path: spec.components.centralServer.kubeSpec.overlays
            value:
            - apiVersion: v1
              kind: Service
              name: xcp-central
              patches:
              - path: spec.type
                value: LoadBalancer
