---
apiVersion: install.tetrate.io/v1alpha1
kind: ControlPlane
metadata:
  name: controlplane
  namespace: istio-system
spec:
  hub: ${registry}
  telemetryStore:
    elastic:
      host: ${elastic_host}
      port: 9200
      version: 7
      protocol: https
      selfSigned: true
  managementPlane:
    host: ${tctl_host}
    port: 8443
    clusterName: ${cluster}
  meshExpansion: {}
  components:
    xcp:
      kubeSpec:
        deployment:
          replicaCount: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        overlays:
        - apiVersion: install.xcp.tetrate.io/v1alpha1
          kind: EdgeXcp
          name: edge-xcp
          patches:
          - path: spec.components.centralServer.kubeSpec.service.annotations
            value:
              metallb.universe.tf/address-pool: tsb
    istio:
      kubeSpec:
        deployment:
          hpaSpec:
            maxReplicas: 10
            metrics:
            - resource:
                name: cpu
                targetAverageUtilization: 75
              type: Resource
            minReplicas: 1
          replicaCount: 1
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
        overlays:
        - apiVersion: install.istio.io/v1alpha1
          kind: IstioOperator
          name: tsb-istiocontrolplane
          patches:
          - path: spec.values.global.proxy
            value:
              resources:
                limits:
                  cpu: 80m
                  memory: 96Mi
                requests:
                  cpu: 40m
                  memory: 56Mi
    oap:
      kubeSpec:
        deployment:
          replicaCount: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
    hpaAdapter:
      kubeSpec:
        deployment:
          replicaCount: 1
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
        service:
          type: ClusterIP
    onboarding:
      operator:
        kubeSpec:
          deployment:
            replicaCount: 1
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 50m
                memory: 128Mi
          service:
            type: ClusterIP
      repository:
        kubeSpec:
          deployment:
            replicaCount: 1
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 10m
                memory: 32Mi
          service:
            type: ClusterIP
    collector:
      kubeSpec:
        deployment:
          replicaCount: 1
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi